MAX_OCCUPANCY: 5
MAX_VOXELS: 20000
GRID_BOUNDS: [0, -40.0, -3, 70.4, 40.0, 1]
ANCHORS: [{
  names: ['Car', 'Van'],
  wlh: [1.6, 3.9, 1.56],
  yaw: [0, 1.501],
  iou_thresh: [0.45, 0.60],
  score_thresh: 0.3,
  center_z: -1.0,
}]
NUM_CLASSES: 1
TRAIN:
  BATCH_SIZE: 4
  LAMBDA: 1.0
  EPOCHS: 60
AUG:
  NUM_SAMPLE_OBJECTS: [15, 0, 0]
