ANCHORS: [{
  names: ['Car', 'Van'],
  wlh: [1.6, 3.9, 1.56],
  yaw: [0, 1.501],
  iou_thresh: [0.45, 0.60],
  center_z: -1.0,
}]
NUM_CLASSES: 1
CNN: 'SpMiddleFHD'
TRAIN:
  BATCH_SIZE: 6
  LAMBDA: 1.0
  LR: 1e-4
AUG:
  NUM_SAMPLE_OBJECTS: [15, 0, 0]
